---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: whoami
  name: whoami-julrun
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    traefik.ingress.kubernetes.io/router.entrypoints: https
spec:
  tls:
    - hosts:
      - whoami.jul.run
      secretName: whoami-julrun-https-cert
  rules:
    - host: whoami.jul.run
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: whoami
                port:
                  name: http
