---
apiVersion: v1
kind: Service
metadata:
  name: traefik-external
  namespace: traefik
  labels: 
    app: traefik
spec:
  type: LoadBalancer
  loadBalancerIP: 10.100.110.200
  selector:
    app: traefik
  ports:
    - name: http
      port: 80
    - name: https
      port: 443
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-internal
  namespace: traefik
  labels:
    app: traefik
spec:
  type: LoadBalancer
  loadBalancerIP: 10.100.110.201
  selector:
    app: traefik
  ports:
    - name: http
      port: 80
      targetPort: 81
    - name: https
      port: 443
      targetPort: 444
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-dashboard-lb
  namespace: traefik
  labels:
    app: traefik
spec:
  type: LoadBalancer
  loadBalancerIP: 10.100.110.202
  selector:
    app: traefik
  ports:
    - name: http
      port: 80
      targetPort: 8080
