---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: whoami
  name: whoami-xdna
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    traefik.ingress.kubernetes.io/router.entrypoints: https
spec:
  tls:
    - hosts:
      - whoami.xdna.net
      secretName: whoami-xdna-https-cert
  rules:
    - host: whoami.xdna.net
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: whoami
                port: 
                  name: http
