---
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik
  namespace: traefik
  labels:
    app: traefik
data:
  static.yaml: |
    api:
      dashboard: true
      insecure: true
    ping: {}
    log:
      level: 'INFO'
    entryPoints:
      traefik:  # Dashboard port
        address: ':9090'
      http:  # External http -> https redirect
        address: ':80'
        http:
          redirections:
            entryPoint:
              to: 'https'
      https:  # External https
        address: ':443'
        http:
          tls: {}
      internal-http:  # Internal http -> https
        address: ':81'
        http:
          redirections:
            entryPoint:
              # This redirects to internal-https. We need to use the port
              # on the service, not the pod, and the LB service is on
              # port 443, as internal and external are different LB
              # services.
              to: ':443'
      internal-https:  # Internal https
        address: ':444'
        http:
          tls: {}
      internal-http-no-redirect:  # Internal http
        address: ':8080'
    providers:
      kubernetesCRD: {}
      kubernetesIngress: {}
      file:
        directory: '/config'
    serversTransport:
      insecureSkipVerify: true
